In [13]:
import pandas as pd

# Define questions
QUESTIONS = ['CONTENT', 'HAPPY', 'LIFE_SAT', 'MENTAL_HEALTH', 'PHYSICAL_HLTH', 'WORRY_SAFETY', 'EXPENSES']

# Define dictionary of countries
COUNTRIES_AND_CODES = {
    1: "Argentina",
    2: "Australia",
    3: "Brazil",
    4: "Egypt",
    5: "Germany",
    6: "India",
    7: "Indonesia",
    8: "Israel",
    9: "Japan",
    10: "Kenya",
    11: "Mexico",
    12: "Nigeria",
    13: "Philippines",
    14: "Poland",
    16: "South Africa",
    17: "Spain",
    18: "Tanzania",
    19: "Turkey",
    20: "United Kingdom",
    22: "United States",
    23: "Sweden",
    24: "Hong Kong"
}

# Open csv files

df_collapse = pd.read_csv("/Users/parriagadap/notebooks/PabloArriagada/global_flourishing_study/gfs_collapse.csv")
df_svy = pd.read_csv("/Users/parriagadap/notebooks/PabloArriagada/global_flourishing_study/gfs_svy_original.csv")

# Edit df_svy
# Separate survey column by the "-" character. Name columns COUNTRY AND WAVE
df_svy[['COUNTRY', 'WAVE']] = df_svy['survey'].str.split('-', expand=True)
df_svy = df_svy.drop(columns=['survey'])

# Change country codes to country names
df_svy['COUNTRY'] = df_svy['COUNTRY'].astype(int)
df_svy['COUNTRY'] = df_svy['COUNTRY'].map(COUNTRIES_AND_CODES)

# Make WAVE in the format of Year {number}
df_svy['WAVE'] = "Year " + df_svy['WAVE']

# Merge df_collapse and df_svy
df = pd.merge(df_collapse, df_svy, on=['COUNTRY', 'WAVE'], suffixes=('_collapse', '_svy'))

# For each question, calculate the difference between the collapsed and survey data
for question in QUESTIONS:
    df[f'{question}_diff'] = df[f'{question}_collapse'] - df[f'{question}_svy']
    df[f'{question}_ratio'] = df[f'{question}_collapse'] / df[f'{question}_svy']

df.to_csv("/Users/parriagadap/notebooks/PabloArriagada/global_flourishing_study/gfs_diff.csv", index=False)

In [7]:
df_collapse

,COUNTRY,WAVE,CONTENT,HAPPY,LIFE_SAT,MENTAL_HEALTH,PHYSICAL_HLTH,WORRY_SAFETY,EXPENSES
0,Argentina,Year 1,7.873458,7.357079,7.290908,7.652747,7.229573,3.743349,3.954223
1,Australia,Year 1,7.095188,6.746841,6.488864,6.692956,6.367256,7.176096,6.643989
2,Brazil,Year 1,7.393251,7.060585,6.935663,7.206273,6.911128,3.745115,3.881013
3,Egypt,Year 1,8.034157,6.528899,8.000717,9.245224,7.081635,6.456053,5.488974
4,Germany,Year 1,7.043413,6.751049,6.572413,6.859140,6.488572,6.711648,6.136501
5,India,Year 1,8.096366,6.712011,7.277359,7.624567,7.159923,4.099636,4.305411
6,Indonesia,Year 1,8.440737,7.843481,7.724559,8.363864,8.001274,6.417385,6.025047
7,Israel,Year 1,8.136012,7.828876,7.510299,8.527537,8.067987,7.334632,7.460349
8,Japan,Year 1,5.273817,5.859315,5.449727,6.049382,5.671818,5.443757,5.194485
9,Kenya,Year 1,8.227566,7.289644,5.964935,8.795940,8.118011,4.946088,4.799413
10,Mexico,Year 1,8.278501,7.714450,7.696232,8.298156,7.517470,4.650230,4.834890
11,Nigeria,Year 1,7.983994,7.210490,6.644010,8.825932,8.357825,5.295019,5.148874
12,Philippines,Year 1,8.491505,7.275640,7.409127,7.939342,7.616741,5.870387,5.334762
13,Poland,Year 1,6.636568,7.403676,6.448344,7.876099,7.437689,6.516280,6.677486
14,South Africa,Year 1,7.679191,6.899698,6.197174,8.395886,7.621956,5.486330,5.358955
15,Spain,Year 1,7.412552,6.655751,6.519770,7.301042,6.518560,4.870469,4.566755
16,Tanzania,Year 1,7.891262,6.675904,5.402057,9.267483,7.892347,5.973533,5.823919
17,Turkey,Year 1,7.210833,5.589537,5.332614,6.274314,6.589753,5.269787,4.588855
18,United Kingdom,Year 1,6.710144,6.483626,5.752461,6.613533,6.287247,6.081901,5.917804
19,United States,Year 1,7.232343,6.953732,6.742012,7.133288,6.720034,6.920342,6.435362
20,Sweden,Year 1,7.137582,6.765682,6.853947,7.050171,6.172139,7.159282,7.007782
21,Hong Kong,Year 1,6.248930,6.981336,5.246669,6.502261,7.123816,5.381601,6.751734